apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackhole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackhole
  template:
    metadata:
      labels:
        app: blackhole
    spec:
      containers:
        - name: blackhole
          image: antoniogotev/blackhole-html:latest
          ports:
            - containerPort: 80
